### ISSUE TITLE
Doesn't work for me on Linux Mint 18.3

### ISSUE THREAD

**Issue by arnauldb** [paulpacifico/shutter-encoder#1]
Hello,
I tried both the appimage and.deb and each time I try to convert a .mp4 file to any other format I receive this error:

> FFPROBE : /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> FFMPEG : 

And in the console:

> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory

Thank you

**Comment by paulpacifico** [comment]
Hello, 
Thank for this post,

Here is the library to add into "/usr/lib/Shutter Encoder/**usr/lib/x86_64-linux-gnu/**"

[libcdio_paranoia.so.zip](https://github.com/paulpacifico/shutter-encoder/files/4769332/libcdio_paranoia.so.zip)

Let me know if it still missing some libraries, i removed some shared libraries included with ffmpeg because there some conflicts on Red Hat distributions (Cent OS & Fedora).

Also i've got some troubles with Linux Mint and Java, dialog windows won't open...

I am downloading Linux Mint 18 for testing.

Regards,
Paul.

**Comment by paulpacifico** [comment]
> Hello,
> I tried both the appimage and.deb and each time I try to convert a .mp4 file to any other format I receive this error:
> 
> > FFPROBE : /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > FFMPEG :
> 
> And in the console:
> 
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> > /usr/lib/Shutter Encoder/usr/bin/Library/ffprobe: error while loading shared libraries: libcdio_paranoia.so.2: cannot open shared object file: No such file or directory
> 
> Thank you

**Comment by arnauldb** [comment]
> Let me know if it still missing some libraries

Thank you. Now I am missing libcdio_cdda.so.2

**Comment by paulpacifico** [comment]
Thank for reply,

So there is a link with all unused libraries from FFmpeg : https://we.tl/t-1uRN6OwFNM

If you can only add needed libraries and say me which one i have to add this could be very usefull for me.

Paul.

**Comment by paulpacifico** [comment]
So i've installed Mint 18 and Mint 18.3 and got the same problem, i can't get it work...
I still try to found what's goes wrong, but if you upgrade to 19.3 this will resolve encoding problem.
Paul.

**Comment by arnauldb** [comment]
Ok, I will update to 19.3. Thank you for your work.
