### ISSUE TITLE
Can not activate AV1 and H265 Hardware acceleration (NVENC)

### ISSUE THREAD

**Issue by hansnolte** [paulpacifico/shutter-encoder#111]
Hello everyone.

unfortunately only H264 hardware acceleration works for me.
AV1 and H265 give me the following error message.
(Latest Nvidia Studio Driver is installed)
![AV1](https://user-images.githubusercontent.com/7922627/209963119-7f4e648c-3f67-4b9c-9ad3-f026a70d568f.jpg)

The FFmpeg binaries (from Today) I had updated by hand, but has brought nothing, so back again.

I had read in this thread that you should swap your driver, game to studio or the other way around.
I hope there is another solution, because I didn't really want to do that.
It runs otherwise everything so nice and fast and stable.
And in older Shutter Encoder Versions, H265 ran with NVENC.
https://github.com/paulpacifico/shutter-encoder/issues/104#issuecomment-1354291123

A little tip would be nice!

Many greetings and my specs

WIN 10 - 22H2
GTX 1070
Latest Nvidia Studio Driver 527.56
Shutter Encoder 16.6

**Comment by paulpacifico** [comment]
Hi,

The GTX 1070 does not support AV1 encoding, for the H.265 function could you please send me the log by right-clicking on the '**Progress status**' section -> '**Show console**' after clicking on hardware acceleration.

Thanks,
Paul.

**Comment by hansnolte** [comment]
> Hi,
> 
> The GTX 1070 does not support AV1 encoding, for the H.265 function could you please send me the log by right-clicking on the '**Progress status**' section -> '**Show console**' after clicking on hardware acceleration.
> 
> Thanks, Paul.

Hi Paul,
thank you very much for your answer.

Too bad my card doesn't support hardware acceleration for AV1.

Okay, here the log for H265 hardware acceleration.

Many greetings
Hans

`Befehl: -hwaccels"

cuda
dxva2
qsv
d3d11va
vulkan

Befehl: -f lavfi -i nullsrc -t 1 -c:v hevc_nvenc -s 640x360 -f null -"

ffmpeg version N-109193-gfecd291869 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --disable-debug --disable-w32threads --enable-sdl2 --enable-gpl --enable-version3 --enable-fontconfig --enable-iconv --enable-libass --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsnappy --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libxvid --enable-libgsm --enable-libsvtav1 --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-amf --enable-vulkan --enable-libglslang --enable-schannel --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-libs=-liconv --shlibdir=/local64/bin-video
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 54.100 / 59. 54.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.101 /  8. 50.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, lavfi, from 'nullsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_nvenc))
Press [q] to stop, [?] for help
[hevc_nvenc @ 000002b8f74e9b00] B frames as references are not supported
[hevc_nvenc @ 000002b8f74e9b00] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Befehl: -f lavfi -i nullsrc -t 1 -c:v hevc_qsv -s 640x360 -f null -"

ffmpeg version N-109193-gfecd291869 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --disable-debug --disable-w32threads --enable-sdl2 --enable-gpl --enable-version3 --enable-fontconfig --enable-iconv --enable-libass --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsnappy --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libxvid --enable-libgsm --enable-libsvtav1 --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-amf --enable-vulkan --enable-libglslang --enable-schannel --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-libs=-liconv --shlibdir=/local64/bin-video
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 54.100 / 59. 54.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.101 /  8. 50.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, lavfi, from 'nullsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
[hevc_qsv @ 000002108c119b00] Error initializing a MFX session: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Befehl: -f lavfi -i nullsrc -t 1 -c:v hevc_amf -s 640x360 -f null -"

ffmpeg version N-109193-gfecd291869 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --disable-debug --disable-w32threads --enable-sdl2 --enable-gpl --enable-version3 --enable-fontconfig --enable-iconv --enable-libass --enable-libdav1d --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsnappy --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzimg --enable-lzma --enable-zlib --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libxvid --enable-libgsm --enable-libsvtav1 --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-amf --enable-vulkan --enable-libglslang --enable-schannel --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-libs=-liconv --shlibdir=/local64/bin-video
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 54.100 / 59. 54.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.101 /  8. 50.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, lavfi, from 'nullsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_amf))
Press [q] to stop, [?] for help
[hevc_amf @ 000001f2f2729f00] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
`

**Comment by paulpacifico** [comment]
Your GPU does not supports B-frames which is very important for the H.265 codec. I dont understand how it was able to work before because this is not a software issue but an hardware limitation.

**Comment by hansnolte** [comment]
Hi Paul,
happy new Year.

>Your GPU does not supports B-frames which is very important for the H.265 codec. 


Yes you are right.
But it supports all other H265 features.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

And the hardware acceleration for H265 works in XMedia Recode with my Card.
https://www.xmedia-recode.de/hilfe/vcodec/nvenc_h265.php

**Comment by paulpacifico** [comment]
Thanks, Happy new year too!

I suppose it works on XMedia Recode because it uses an older version of Nvidia codecs.

Unfortunately I can't do much in your case, because I need to update the Nvidia codecs and I have no control that.

Paul.

**Comment by hansnolte** [comment]
> Unfortunately I can't do much in your case, because I need to update the Nvidia codecs and I have no control that.

Too bad.
But anyway, luckily I don't need H265 that often.

Many thanks for your effort
Hans
