### ISSUE TITLE
[enhancement] Location for Settings and Functions

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#12]
On Mac, Settings.xml and Functions are in Documents.

There appears to be no option for choosing a location.

Using Shutter Encoder 14.6 - Mac 10.11.6.

**Comment by chenlung** [comment]
There appears to be no option for choosing a location.

**Comment by paulpacifico** [comment]
Someone also request me this option, just curious why you need to change it? and where?

**Comment by chenlung** [comment]
I have a folder within Documents called 'Software' (there are others for unrelated things); this is where I keep such settings.

**Comment by paulpacifico** [comment]
Ok great, i will add this.

**Comment by ltdeta** [comment]
windows v15.3
I use the portable version.
Here, saving the configuration and functions in the program directory would be a better choice.

Suggestion:
3 options:
- 1. default (c:\Users\...\Documents\Shutter Encoder).
- 2. using portable directory (if portable version)
- 3. own selection of the directory

**Comment by paulpacifico** [comment]
Currently I have a problem, because the app need to know where the settings.xml is located if I add the ability to change the location of it, I need to write into an other file where the settings.xml file is.
On Windows I could you use the registry but I don't know how to handle this on Mac & Linux.

The other problem is the users rights, if I allow to save the settings.xml into the app folder it could be refused to write into. That's why I use the "\Documents" folder. Also on Linux the .AppImage is read only which is a real problem.

So I would like to allow the user to change the settings.xml location but currently I'm stuck.

If someone has any idea I'm curious to know.

**Comment by rauldipeas** [comment]
> Currently I have a problem, because the app need to know where the settings.xml is located if I add the ability to change the location of it, I need to write into an other file where the settings.xml file is. On Windows I could you use the registry but I don't know how to handle this on Mac & Linux.
> 
> The other problem is the users rights, if I allow to save the settings.xml into the app folder it could be refused to write into. That's why I use the "\Documents" folder. Also on Linux the .AppImage is read only which is a real problem.
> 
> So I would like to allow the user to change the settings.xml location but currently I'm stuck.
> 
> If someone has any idea I'm curious to know.

On Linux, you can set it to `$HOME/.config/shutter-encoder` or something similar into this `.config` folder.

I'm Brazilian and already have `$HOME/Documentos` for my _documents_ folder, it's very bothering to have this folder duplicated with the name in another language.

**Comment by RafaelLinux** [comment]
Continuing with this issue, some time ago I wrote about same issue in openSUSE. SE creates a "Documents" folder, but my local language is Spanish. I wrote to Paul about if I guess something more about this question, I'll tell him about it, and this is what I can  contribute about this issue:
The file `~/.config/user-dirs.dirs` contains all XDG folders name and their local language equivalent, like this:
```
XDG_DESKTOP_DIR="$HOME/Escritorio"
XDG_DOWNLOAD_DIR="$HOME/Descargas"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/Público"
XDG_DOCUMENTS_DIR="$HOME/Documentos"
XDG_MUSIC_DIR="$HOME/Música"
XDG_PICTURES_DIR="$HOME/Imágenes"
XDG_VIDEOS_DIR="$HOME/Vídeos"
```
So `XDG_DOCUMENTS_DIR` in openSUSE contains the right folder name to store SE setting. 

I wish it could help yet to fix the folder settings issue.

**Comment by snocodile** [comment]
Is there a fix for the AppImage version yet? It's kind of annoying for users with non-English locales as it creates the `Documents` folder every time.

**Comment by RafaelLinux** [comment]
I can't help more about. I put exactly the file and environment variables that ShutterEncoder should inspect to solve this issue. Several months passed but is like my post was ignored  :(

**Comment by RafaelLinux** [comment]
I'm sorry Paul, but bad news:  I tried "Shutter Encoder 17.0 Linux 64bits.AppImage" and it continues creating "Documents/Shutter Encoder ..." folder.

**Comment by paulpacifico** [comment]
It will be for the next release.

**Comment by RafaelLinux** [comment]
Perfect then!! I'm willing to delete that weird folder from my system that I thought enhancement was integrated in last published version. 

THANK YOU for your work, I'm sure it's very difficult to have a multiplatform application running fine in all operating systems.

**Comment by MrPenguin07** [comment]
> It will be for the next release.

Still creates ~/Shutter Encoder smack bang in users home dir.
Really appreciate if it can comply with XDG standard and place the config inside ~/.config

Regards

**Comment by jdahdah** [comment]
Was this ever released? It's cluttering my `~/` home folder on MacOS and I don't find a setting to change it.

**Comment by paulpacifico** [comment]
"Shutter Encoder" folder can be moved into **/Library/Preferences/** or **/Library/Application Support/**

**Comment by jdahdah** [comment]
> "Shutter Encoder" folder can be moved into **/Library/Preferences/** or **/Library/Application Support/**

It worked for `~/Library/Preferences/` in my home directory.

`~/Library/Application Support/` did not work, the app kept recreating the settings in my Home folder (though I'm not sure if you actually meant the `/Library/Application Support/` at the system root, as you didn't include the `~` above).

In any case it's solved for me. Thanks!
