### ISSUE TITLE
Audio sample rate should use dropdown

### ISSUE THREAD

**Issue by hmturnbull** [paulpacifico/shutter-encoder#120]
I've been using Shutter Encoder 16.8 to quickly convert some 48k files to 41k, and the toggle button makes selecting the desired sample rate needlessly tedious.  I end up having to click it quite a few times, depending on how many times I click past the desired option.

![ShutterEncoder - sample rate toggle is tedious](https://user-images.githubusercontent.com/52052397/222034479-958f84f5-a002-456a-8f44-be2af42e1d3f.jpg)

There are too many different sample rates to choose from for a toggle button to make sense.  I think this toggle should be replaced with a drop-down, similar to the ones used for framerates.  This is, after all, how almost every software handles sample rates--and for good reason; a drop-down would reduce the number of clicks down to 2.

**Comment by paulpacifico** [comment]
Thanks for your feedback,

I have currently removed some unused values for the next release which should be out during this week, because changing to a drop down menu is quite a big change to the UI.

Paul.
