### ISSUE TITLE
Color Shift in ProRes

### ISSUE THREAD

**Issue by hansnolte** [paulpacifico/shutter-encoder#122]
Hi Paul,

I import a 8-Bit PNG-Image Sequence with Alpha.

Export ProRes 4444 (and also in XQ) from Shutter has a Color Shift.
GoPro CineForm from Shutter is okay.

![Shutter-ProRes-ColorShift](https://user-images.githubusercontent.com/7922627/224290528-9b3cfa98-540f-431c-9a53-aaa610b1d753.png)

Win 10
Shutter Encoder v16.9

Bye 
Hans

EDIT:
Just looked up again.
The color shift was also already in Shutter Encoder 16.8

**Comment by hansnolte** [comment]
Why is the thread closed?
The bug is still in Shutter Encoder v17.1.

**Comment by Remdrift** [comment]
I am also seeing color shifts when exporting in ProRes from a PNG sequence. Not sure if I'm doing something wrong.
