### ISSUE TITLE
Is possible stretch totally an video area to vertical ?

### ISSUE THREAD

**Issue by Augusto7743** [paulpacifico/shutter-encoder#124]
Is possible stretch totally an video image to vertical ?

Hello Paul. All good with you ?

An video 1920X1080P with the video area exactly as the image below being the red area and the yelow area not having any video image.
Shutter Enconder have any feature allowing select an video area and stretching totally to horizontal or vertical ?
In that video need select the red area and stretch totally to vertical.

Thanks for reading.
Have an nice day.

![se2](https://user-images.githubusercontent.com/21184987/230230504-643557b1-5d87-4457-8f7c-82c00eb139f1.jpg)

**Comment by paulpacifico** [comment]
Hi,
You should be able to achieve your goal using the '**Crop image**' feature from the '**Edit media content**' window, and use the '**Force display**' and '**Scale**' options from the '**Settings**' window (right-panel).
Paul.

**Comment by Augusto7743** [comment]
Hello Paul ... thank for replying ... all good with you ?
Video was stretched using the informations above.
That was for testing =)

Have an nice week.

**Comment by paulpacifico** [comment]
Great!
Yes everything is fine, I'm finishing the next release ;-)
