### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by Dilsh93** [paulpacifico/shutter-encoder#126]
1. Please add new function for Image creation: Category>Image> .apng

2. Add apng fps Level 15 fps to 60 fps & add Custom fps value input box

3. Increase .gif fps Level 15 fps to 60 fps & add Custom fps value input box

**_Please add this features next update_**

**Comment by paulpacifico** [comment]
I've added .apng format and add many framerates values for the next release.

Paul.
