### ISSUE TITLE
Settings folder on linux

### ISSUE THREAD

**Issue by schoenid** [paulpacifico/shutter-encoder#127]
The settings are stored to:
`/home/<user>/Documents/Shutter Encoder`

This is bad, because it creates two new directories, visible in the user area, without to ask. For me this is a "No Go".
I'm native german speaking and this results in "Documents" near "Dokumente". I like controlled order, but this leads to an uncontrolled state of my directory tree.

A better solution would be to use `~/.local/share/Shutter Encoder`, because this is normally hidden. Or the user could be asked, to configure a directory of it's own choice. I did not find any setting for this.

Btw: The application itself looks great.
If you correct this, I would give it another try ...

**Comment by paulpacifico** [comment]
Hi,

I will change it to a new location for the next release (v17.1) under `/home/<user>/Shutter Encoder`

Paul.

**Comment by schoenid** [comment]
Great!
Thank you very much!
