### ISSUE TITLE
[BUG] Using Watermark in Shutter Encoder

### ISSUE THREAD

**Issue by JeditPro** [paulpacifico/shutter-encoder#128]
Hi Paul Pacifico,

I use Shutter Encoder to create Poxies from the 4k videos I edit.

Proxies are created normally if no watermark is added to identify the proxies in Edit Media Content. (See video 01 from the link)

But when I add a watermark to identify the proxies in Edit Media Content, all videos are the same length as the first video in the list. (See video 02 from the link)

An alternative tiresome way to resolve this is to view all videos in Edit Media Content by clicking the Next button. (See video 03 from the link)

If it is possible, can you fix this? It will help a lot as I like to identify my proxy files with a watermark to guide me while editing.

The video files showing the problem are in this link below
https://drive.google.com/file/d/1DY6h19_c96L4K_PXcNgaSNLRCmBgrZ1X/view?usp=sharing

**Comment by paulpacifico** [comment]
Hi,

Thank you so much for your video capture, you're right there is a huge bug here.
I've corrected into my code, I will make a new version because of this critical issue.

Thanks again for your help,
Paul.

**Comment by JeditPro** [comment]
I'm happy to help! Thanks for your work!
