### ISSUE TITLE
Add an option to create a queue for encodes

### ISSUE THREAD

**Issue by cleanerspam** [paulpacifico/shutter-encoder#131]
Currently you have to wait for process to complete and then add another set of files ,
 It would be very convenient if  user can schedule jobs as many as he wants and Shutter starts the next job in the queue 
as soon as the previous job completes  .
I know new instance can be created but  It takes up all resources on using multiple instances .

**Comment by paulpacifico** [comment]
You can access to the 'Render queue' window from the 3 lines icon next to the 'Start function' button.

**Comment by samueloph** [comment]
@paulpacifico I see mentions of this "3 lines icon" everywhere on the internet, but I can't find this anywhere in the UI, is there a screenshot provided anywhere? Is this an icon that only shows up under certain functions?

**Comment by paulpacifico** [comment]
It's only available for certain functions, which function are you using? You can see this 3 lines with any audio codecs.

Paul.

**Comment by samueloph** [comment]
I could not find it for the extract audio function

**Comment by paulpacifico** [comment]
Indeed it's not available with this function.
