### ISSUE TITLE
Allowing giving custom name to output file  

### ISSUE THREAD

**Issue by cleanerspam** [paulpacifico/shutter-encoder#132]
Current behavior of Shutter is to Add codec name or function name in end to the output file name 
It does not allows giving any name which user wants for the file , It would reduce a lot of post encoding renaming job .

**Comment by paulpacifico** [comment]
You can use the 'Replace suffix' checkbox from the cog icon top left corner of the main window.

**Comment by nik196363** [comment]
When downloading a video with a Russian title, the file is downloaded without a title.
