### ISSUE TITLE
When encoding, is VSync disabled?

### ISSUE THREAD

**Issue by Augusto7743** [paulpacifico/shutter-encoder#135]
Hello Paul.
When enconding the ffmpeg command the vsync is disabled ?
In ffmpeg docs

"Use -vsync 0 option with decode to prevent FFmpeg from creating output YUV with duplicate and extra frames"

Thanks for doing Shutter Enconder.

**Comment by paulpacifico** [comment]
Hello,

The vsync is set to default according to FFmpeg documentation, you can switch to other modes from the top left cog icon then change the '**Set framerate mode:**' option.

Paul.
