### ISSUE TITLE
[Feature Request ] Option to embed subtitle (.srt) file in a video file

### ISSUE THREAD

**Issue by cleanerspam** [paulpacifico/shutter-encoder#136]
Please add option to  softcode/embed  subtitle from a pre-existing .srt file inside a video file .
I tried adding a srt file to a mkv file but there was only option to manually create subtitles and then burn or embed them but no option to automatically add subtitles from a srt file or any other subtitle format

**Comment by paulpacifico** [comment]
Use the 'Rewrap' function then open the 'Edit media content' window from the right panel, check 'Add subtitles' then choose the .srt file(s) you want to embed into your video.
Paul.
