### ISSUE TITLE
[feature] preset select when using QSV encoder 

### ISSUE THREAD

**Issue by BuyMyMojo** [paulpacifico/shutter-encoder#137]
When using the QSV encoder for `AV1`, `H264`, `HEVC`, `VP9` and  `MPEG2` you can use the `-preset:v` option with an input of 7(veryfast) to 1(veryslow) but when enabling the Hardware encoder in shutter encoder the `Force preset` button is greyed out.

This is specifically with an Intel A770 GPU in my case but I think the option is there for iGPU encoders too

**Comment by paulpacifico** [comment]
The force preset is not greyed out for me for H.264/5 encoders.
With AV1 & VP9 encoders use the '**Force speed**' option (which send the preset:v _number_)
Paul.

**Comment by BuyMyMojo** [comment]
Oops yeah this is my fault, I skimmed over too quickly and confused it with `force tune` that is my bad.
