### ISSUE TITLE
[feature] Auto-crop

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#14]
1. 'Crop image…' [Editing / Old / Archiving codecs] or 'Crop…' [Output / Broadcast codecs].
2. The user navigates to a point of activity in the video (i.e. not the start, which is often black).
3. Click 'Auto' so that Shutter will determine the black area to crop off (can be refined manually after).

This could be more precise and speedier.

**Comment by paulpacifico** [comment]
Great idea, i write this to my do to list.

**Comment by chenlung** [comment]
I think this has been implemented (the 'auto' option)?

**Comment by paulpacifico** [comment]
Yes!
