### ISSUE TITLE
[bug] ffmpeg command syntax error when supplying `-filter_complex` option with float `fps` parameter

### ISSUE THREAD

**Issue by bashiron** [paulpacifico/shutter-encoder#143]
# Steps to reproduce
1. Select any video file
2. Set function parameters to "Image" function with `.gif` format (most probably works with any function anyway)
3. Set image parameters to `fps: 29,97fps` and the rest (scale, rotation, etc) to anything
4. Open the render queue
5. Add function to queue and launch

# Observed result
Processing will fail. Click on "Show console"
On the `ffmpeg` tab the line that gets printed at the start of conversion is the `ffmpeg` command (line that starts with `Command:`), i will reference this section of the log as `ffmpeg command`.
My `ffmpeg command` reads
```
Command: -threads 0 -hwaccel none -i "/home/bashiron/Videos/2023-07-01 12-26-22.mp4" -filter_complex "scale=640:-1,crop='640:360:0:(ih-oh)*0.5',split[a][b];[a]palettegen[p];[b][p]paletteuse,fps=29,97[out]" -map "[out]" -q:v 0 -sws_flags bicubic -an -y "/home/bashiron/shutter encoder output/2023-07-01 12-26-22.gif"
```
At the end of the log the error printed reads
```
[AVFilterGraph @ 0x6c0be80] No such filter: '97'
Error initializing complex filters.
Filter not found
```

# Expected result
New GIF video file.

# Observation
For some time i thought my `ffmpeg` version might be at fault, because i recently switched from the pacman repos version to the AUR version and it may not have the required filter built-in.
But upon looking at the `ffmpeg command` it seems the `fps=29,97[out]` part of the `-filter_complex` option has a syntax problem since ffmpeg seems to be interpreting the `97` as a filter.
This is most likely reproducible with any other float type fps parameter.

# Possible solution
When setting the `fps` parameter in the `-filter_complex` option: surround value in single quotes.

# Software/OS versions
Arch Linux x86_64

**Comment by bashiron** [comment]
Oh btw after that i tried the same settings but with `30` fps and it worked

**Comment by paulpacifico** [comment]
Thanks for this feedback, I've corrected the issue for the next release.
Paul.
