### ISSUE TITLE
App GUI is hidden on a Win 11 PC with dual GPU with no connected monitor to second GPU

### ISSUE THREAD

**Issue by RimasRaV1** [paulpacifico/shutter-encoder#145]
v16.9 was fine. v17.2 and v17.3.
How to reproduce:
On Win 11 install a second GPU with no connected monitor. Install or upgrade Shutter Encoder v17.2 or 17.3. Start the app. The app shows the splashscreen, then dissapears. Disable the second GPU in Device Manager - v17.3 of the the app starts normally. Enable GPU - it hides again.
Video of this behavior: https://youtu.be/DSgZbo_8qHk

**Comment by paulpacifico** [comment]
Thanks a lot for your screen record,

Could your try this:

- Download this file: https://www.shutterencoder.com/Paul/JRE.zip

- Extract-it.

- Replace this file "C:\Program Files\Shutter Encoder\JRE" with the extracted JRE folder.

- Run the app and let me know if it solve the issue.

Thanks,

Paul.

**Comment by RimasRaV1** [comment]
> * Download this file: https://www.shutterencoder.com/Paul/JRE.zip
> * Extract-it.
> * Replace this file "C:\Program Files\Shutter Encoder\JRE" with the extracted JRE folder.
> * Run the app and let me know if it solve the issue.

Hi, Paul. No, unfortunately, it didn't change the behavior of the app. Tried it several times, and restarted the PC - no window of SE is showing up.

**Comment by RimasRaV1** [comment]
> * Run the app and let me know if it solve the issue.
Another issue with this JRE is - when I run the app with second GPU dissabled and try to move the window - elements in the app window (buttons, video preview, etc.) dissaper. I had this behaviour with previous versions of the app. After reinstalling v17.3 (with default JRE and with disabled second GPU) contentens of the window do not dissaper.

**Comment by DaBenjamins** [comment]
I have this same issue, I have a AMD 7900X GPU (has iGPU) and a 7900 xtx GPU

**Comment by GlitterKill** [comment]
Same thing for me.  No GUI on Windows 11.  AMD 7900X + AMD 7900 XTX.

**Comment by tetraDB** [comment]
I'm also experiencing this. I beleive (massive guess here) it's rooted in having multiple displays.
I only have a single GPU, but run two monitors, different resolutions. (Windows 10)
I noticed having issues with dragging it from one to the other, and back. The cursor ended up being misaligned with the GUI and at one point the window seemed to be way larger, transparent, and blocking mouse clicks on other windows in the background.
Possibly started happening after I moved it to my secondary monitor and closed it there.

It's pernamently awol now when I start the app, but I have found a way to get it to appeare again, although inconsistent.

While the window is focused, by clicking it in the task bar, I spam the switch display shortcut (WinKey + Shift + Left then Right...) a few times.
Then I defocus the window (by focusing a different window), then focus back to the shutter window, repeat the process a few times, until it shows up eventualy when I refocus the window. (very inconsistent indeed, but eventually it shows up)

This is basically why I suspect having multiple displays is causing the issue. Windows 10 has always been bad at managing app windows on multiple displays.

**Comment by jamie-macleod** [comment]
Hi there - just to confirm that this issue is still present.  I'm on Windows 11 with triple monitors (4k@150% scaling +  two 1080p@100% scaling) but only a single GPU (3070Ti).

Not ideal, but the app is still usable with some patience.  Just thought I'd update.

<img width="1013" alt="Screenshot 2023-11-17 091935" src="https://github.com/paulpacifico/shutter-encoder/assets/126464216/d45764d6-eaa2-41d9-939d-e3bb95d453ed">

**Comment by jamie-macleod** [comment]
> Hi there - just to confirm that this issue is still present. I'm on Windows 11 with triple monitors (4k@150% scaling + two 1080p@100% scaling) but only a single GPU (3070Ti).
> 
> Not ideal, but the app is still usable with some patience. Just thought I'd update.
> 
> <img alt="Screenshot 2023-11-17 092511" width="1085" src="https://user-images.githubusercontent.com/126464216/283746625-5e83e58a-d457-4fea-bbf5-df2a7d804a88.png">

Seems my post this morning was a bit quick.  I just opened Shutter Encoder and was prompted to update to v17.7.  At least initially, this seems to have solved the issue!

**Comment by jamie-macleod** [comment]
Another update - the UI still disappears, but it only seems to happen after encoding (or maybe after monitor goes to sleep.  I've only done long encode sessions so hard to confirm).

Either way, it's not a big deal as I'm able to encode and can then restart program if needed.  Just thought I'd give update.

<img width="1079" alt="Screenshot 2023-11-22 090755" src="https://github.com/paulpacifico/shutter-encoder/assets/126464216/a9c45cbe-56c0-4702-ba15-2510b0d17905">

**Comment by paulpacifico** [comment]
Please check this reddit post, it seems to solve the issue: https://www.reddit.com/r/shutterencoder/comments/185rbdm/shutter_encoder_ui_issue_or_not_starting_windows/?utm_source=share&utm_medium=web2x&context=3

Paul.

**Comment by geverin** [comment]
this solved the issue for me

**Comment by RimasRaV1** [comment]
> Please check this reddit post, it seems to solve the issue: https://www.reddit.com/r/shutterencoder/comments/185rbdm/shutter_encoder_ui_issue_or_not_starting_windows/?utm_source=share&utm_medium=web2x&context=3
> 
> Paul.

It solved it for me as well.
