### ISSUE TITLE
NVIDIA NVENC option not available on 17.4 on Windows OS

### ISSUE THREAD

**Issue by bouks** [paulpacifico/shutter-encoder#151]
Maybe cause of this if / elseif section.

If on Windows will not go to the "if AV1" section and therefore not activate nvidianvenc.

Not expert in java, don't know your code, but if it can help.

https://github.com/paulpacifico/shutter-encoder/blob/3d28b67c22ab5fce1d15178ca17dc7e228a50144/src/application/Shutter.java#L19743C20-L19791C69

**Comment by paulpacifico** [comment]
I've re-uploaded the v17.4, please reinstall and let me know it should be working now.

Paul.

**Comment by bouks** [comment]
> I've re-uploaded the v17.4, please reinstall and let me know it should be working now.
> 
> Paul.

Working fine. :)
