### ISSUE TITLE
Preserve Metadata create wrong Tagged and Encoded date

### ISSUE THREAD

**Issue by chenshuo890** [paulpacifico/shutter-encoder#153]
Hi

Thank you very much for the software you created. It has helped me a lot in video encoding, especially the ability to load LUTs and specify color spaces.

A problem I found is that when enable preserve metadata, Tagged and Encoded date generated will be 8 hours earlier than original. The time zone of my computer is GMT+8. 

As the screenshot shows.

It is very hoped that this will be resolved in the future.

Best wishes.

![屏幕截图 2023-09-06 102943](https://github.com/paulpacifico/shutter-encoder/assets/6400324/03c16050-1b0c-4f55-a2fe-b31bfd86a28c)

**Comment by chenshuo890** [comment]
Hi,

Here is the original video. https://1drv.ms/v/s!Aml5w48WUpFMkfY0sd9I3v_tcRhwHg?e=fUaXtt

**Comment by chenshuo890** [comment]
And this is the Function file I usually used.
[HEVC_Rec709-Rec2020HLG_10b.zip](https://github.com/paulpacifico/shutter-encoder/files/12537536/HEVC_Rec709-Rec2020HLG_10b.zip)

**Comment by chenshuo890** [comment]
Thanks for your working.

Shuo

**Comment by paulpacifico** [comment]
That's weird because `-map_metadata 0` is used in my code.

But I removed the `media_creation` tag and it should work has expected.

Here is the launcher to replace in **C:\Program Files\Shutter Encoder** https://we.tl/t-ZzSk6vxZal

**Comment by chenshuo890** [comment]
Thank you so much for your work.

Now the encoder can generate the correct metadata.

Thanks again for your dedication.

Best wishes.
Shuo

![屏幕截图 2023-09-08 124104](https://github.com/paulpacifico/shutter-encoder/assets/6400324/47adcad2-6074-4427-824f-eba1da5e7971)

**Comment by ulliillu** [comment]
Hi,
I have the exact same issue when converting .mov files to .mp4. The UTC gets copied over, but the local timezone shift gets ignored. I have to manually correct it for each file. 
I'm using Shutter Encoder 18.2 on macOS 14.5. How was this solved? I cannot download the WeTransfer file anymore.
Thanks
