### ISSUE TITLE
Adding wav files to convert to mono don't have correct commands

### ISSUE THREAD

**Issue by Disar** [paulpacifico/shutter-encoder#162]
Those input paths should just be one item.
![image](https://github.com/paulpacifico/shutter-encoder/assets/7016049/f9f05675-8b23-4041-8f20-bcf3f8d3de0f)

steps:
-Choose files
-Click burger icon
-Add to queue

**Comment by paulpacifico** [comment]
Thanks, it's corrected for the next release.

Paul.
