### ISSUE TITLE
Binary Release Changes without Version Change

### ISSUE THREAD

**Issue by HarryHung** [paulpacifico/shutter-encoder#185]
Hi!

Thank you for creating this amazing project and sharing it for free. 

I am just wondering is it expected that the binary release on your website could change without version change?

I am asking as the I am trying to install it on macOS via [Homebrew](https://brew.sh/), and [encountered a checksum error due to the binary has changed since the latest version (18.0) first release](https://github.com/Homebrew/homebrew-cask/pull/169914). [Similar situation seems to happen before](https://github.com/Homebrew/homebrew-cask/pull/164363) as well.

If this is expected, [the dev of Homebrew suggests they might disable checksum of your software](https://github.com/Homebrew/homebrew-cask/pull/169914#issuecomment-2020285372). So it would be nice if you could confirm that. 

Thanks!

**Comment by paulpacifico** [comment]
Hi!

Thank for your feedback, yes it was intentional because there was a very small issue on that release so I've rebuilt them and re-uploaded but I know that a dirty way to correct it. It can happens sometimes you might need to disable the checksum indeed.

Paul.

**Comment by HarryHung** [comment]
Thanks for confirming!

**Comment by bevanjkay** [comment]
> but I know that a dirty way to correct it

Why not just push an additional release then?
