### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Peter-Soeiro** [paulpacifico/shutter-encoder#191]
Before using your app, I used to do -> ffmpeg -ss 00:01:00 -to 00:02:00 -i "input.mp4" -c copy "input_cut.mp4"
And it would cut the part in seconds, even in a five-hour video.
But your app seems to "load" the entire video before cutting, which takes a lot longer, like 100x longer.

Can you tell me what's the difference between my command and the one you use?
And why do you use it?

Thanks

**Comment by paulpacifico** [comment]
I think this is because it loads the waveform for the video player, uncheck the '**Show waveform**' option to get a quicker loading.

Paul.

**Comment by Peter-Soeiro** [comment]
I was talking about loading during the cut.

When I cut using my command, it takes 10 seconds.
When I cut using your app, it takes 10 seconds to reach 100%, but then it takes another 5 minutes to actually finish. (or longer depending on the video size), like it's loading the rest of the video before exporting the short clip.

I'm using an HDD and I'm working with vods (6 hours, 20 GB), so I can feel the problem.

My command doesn't get affected by how big the video is, only by how big the cut is.


I hope this is a better explanation of my problem
