### ISSUE TITLE
[BUG] H.264 doesn't output lower than Profile Level 5.1

### ISSUE THREAD

**Issue by Lalovoe** [paulpacifico/shutter-encoder#197]
I noticed that videos encoded with h264 don't go lower than Level 5.1 even if the media should allow for it. According to wikipedia, h264 level 5.1 is sufficient for decoding 3840x2160p @ 30fps or 1920x1080p @ 120fps: https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels But even though I'm only encoding 1280x720p @ 30fps it still defaults to Level 5.1, even though the media fits into Level 3.1. Iit's important to note that Shutter Encoder correctly chooses a higher Level, like 6.1 when doing 8k @ 60fps. The problem is only with automatically choosing lower levels.

If I use a simple command in FFMPEG like `ffmpeg -i <my_video> -c:v libx264 output.mp4`, then FFMPEG will correctly determine the lowest possible Level it can use for the video, which in this case is 3.1. So I am suspecting that there might be an oversight in the ffmpeg command building behind the scenes in the program.

Shutter Encoder seemingly correctly chooses the lowest possible Level for other codecs such as AV1 and H265 in the limited testing I have done.

And of course, the "force profile" option under advanced settings has been left unchecked the entire time during this testing.

I don't know the exact implications of what a Profile Level being too high can do, but I suspect it can make playing back the video on weaker hardware more difficult? (like phones and such, that may only be rated for a Level 4.1 max at 1080p60) I don't know this for sure, but it is just how I would imagine it.

**Comment by paulpacifico** [comment]
Indeed the level 5.1 is applied by default by SE **only for x264** to achieve a **better quality encoding**. Most of materiels can play it easily, otherwise you have to use the '**Force profile**' checkbox.

Paul.
