### ISSUE TITLE
Please add .DirIcon

### ISSUE THREAD

**Issue by probonopd** [paulpacifico/shutter-encoder#2]
Hello, thank you very much for making an AppImage. Currently it is missing a `.DirIcon` file that is required as per the AppDir spec.

> FATAL: .DirIcon is missing in /tmp/.mount_BeingTqg4TV3

You could add a 128x128 png file as your `.DirIcon` inside the AppDir root directory.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2051

**Comment by paulpacifico** [comment]
Hello, the AppImage has been re-uploaded with icon.
https://www.shutterencoder.com/Shutter%20Encoder%20(Linux%20Version%2013.8).AppImage

Thank you very much.
Paul.
