### ISSUE TITLE
preview of custom LUT effects no possiblr

### ISSUE THREAD

**Issue by 0lm** [paulpacifico/shutter-encoder#21]
i added some LUT effects i downloaded for free, but unfortunately when i clcik on preview, no preview windoe pops up. custom LUT effect previewseems bugged... or i dont know how to exactly make shutter encoder previe custom lut effects. i can only see the effects in the final output after starting function.

**Comment by paulpacifico** [comment]
Thanks for your feedback,
What is the extension of your LUTs? do you have any sample for testing?

Keep me informed,
Paul.

**Comment by 0lm** [comment]
Hi, thanks for the response. One of the free LUT packs I downloaded was this one: https://www.rocketstock.com/free-after-effects-templates/35-free-luts-for-color-grading-videos/
They all have *.cube extension.

**Comment by paulpacifico** [comment]
Perfect thanks,
Simply replace the spaces by an other caracter like _ or -
You can use "Rename the file(s)" from file list for batch renaming.

It will be corrected automatically for the next release.
Paul.

**Comment by 0lm** [comment]
The LUT effect Preview does work for custom effects now. Thanks for fixing it!
