### ISSUE TITLE
Ability to disable automatic video preview

### ISSUE THREAD

**Issue by furyzenblade** [paulpacifico/shutter-encoder#212]
![NVIDIA_Share_1L2FChZHSW](https://github.com/user-attachments/assets/2dd69974-97ad-4ca3-9b2a-2581b9c79e84)

I am not sure if this already exists but it doesn't seem to. 
I'd like to have a setting or a hotkey to hide or not see this preview/ video editor mode at all because I don't need it most of the time and it takes up too much screen space.

**Comment by paulpacifico** [comment]
You can disable the video player from the top left cog icon.

Paul.

**Comment by furyzenblade** [comment]
Ah sorry I forgot to update Shutter Encoder to the latest version, I see it in the settings now. Thank you!
