### ISSUE TITLE
The preview position of the added text does not match the actual position.

### ISSUE THREAD

**Issue by EraSun** [paulpacifico/shutter-encoder#213]
Hello! This software is very good, and I am very grateful to you.

I've noticed that when I use the text addition function, the position of the text in the preview does not match the actual position on the screen, which is very frustrating. I'm using the integrated graphics card that comes with the i3-12100. What could be the problem?

Please disregard that my screenshot does not contain HDR content.

![screenshot1](https://github.com/user-attachments/assets/7737c0a1-050f-43eb-8d55-97bc089ff36c)
![screenshot2](https://github.com/user-attachments/assets/d53e3e07-6e6d-41a1-b04c-acb1d49749f9)

**Comment by EraSun** [comment]
> That's strange indeed, could you send me your file for checking?
> 
> Paul.

Of course, this is the OneDrive link for the video.
https://1drv.ms/u/c/809c0f235addc005/EbpF4RfUMfNJndpQNvUOw2EBklhDjgKDye2NFHg_M3yvjg?e=qWszlk

**Comment by paulpacifico** [comment]
Thanks, it's related to your screen dpi which seems to be at 175%, I'm trying to correct this.

Paul.

**Comment by paulpacifico** [comment]
Corrected for the next release.

Paul.
