### ISSUE TITLE
[BUG] Unable to use NVENC encoding at v18.3

### ISSUE THREAD

**Issue by Radium-bit** [paulpacifico/shutter-encoder#217]
Hi paulpacifico.
I upgraded ShutterEncoder from v18.1 to v18.3, and when I tried to encode a video, I found that only the IntelQSV option was available. But I am sure my NVIDIA graphics card is working fine, and other software can call it normally.

**Comment by Radium-bit** [comment]
I solved it by upgrading the NVIDIA drivers, but maybe this means that v18.3 is not backwards compatible?

**Comment by Radium-bit** [comment]
> What do you mean by "is not backwards compatible"? It just need the latest Nvidia drivers.
> 
> Paul.

I'm just worried that it might not work in NVENC mode on some older NVIDIA graphics cards.

**Comment by Augusto7743** [comment]
Have user in another forum saying is possible compile ffmpeg having compatibility with older nvidia GPUs if was copied correctly the nvidia headers in source code. He say more others informations too.
For luck Shutter Enconder allow use an alternate ffmpeg version installed in OS.

**Comment by paulpacifico** [comment]
Yes but I need the latest headers to get the best perfomance and latest options.

Paul.

**Comment by Augusto7743** [comment]
"Yes but I need the latest headers to get the best perfomance and latest options."
You are correct.

latest headers not support nvidia 600 series kepler ? the only way to ffmpeg in current version add support for nvidia 600 is using nvidia headers previous versions ?
