### ISSUE TITLE
A Java Exception has occurred (Windows 7 x64)

### ISSUE THREAD

**Issue by 60fpshacksrock** [paulpacifico/shutter-encoder#22]
I have tried both 14.2 and 14,7 and get the same error. Java on my PC is version 8 update 281.

**Comment by paulpacifico** [comment]
Thanks for the feedback,
Java is embedded into Shutter Encoder, so you don't need to update it from your PC.
I never get this error before, when does this error happens?
Paul.

**Comment by 60fpshacksrock** [comment]
When opening the program.

**Comment by paulpacifico** [comment]
That's so strange...

Could you uninstall Shutter Encoder and Java from your PC, reboot, then try to run the portable app: https://www.shutterencoder.com/Shutter%20Encoder%20(PC%20Version%2014.7).zip

Keep me informed,
Paul.

**Comment by 60fpshacksrock** [comment]
Tried it. Same problem. It could be a Windows 7 issue, though as far as I see, Java still supports Windows 7.
https://www.java.com/en/download/help/sysreq.html

**Comment by paulpacifico** [comment]
It should works on Windows 7 (at least on 64Bits) a friend of mine use Shutter on W7. It should even works on Vista!

But that's a big problem because i have no idea how to make it works, your the first in 8 years of development who had this issue...

Try something, open the command terminal (cmd) then copy/paste (with quotation marks):

`"C:\Program Files\Shutter Encoder\JRE\bin\java.exe" -jar "C:\Program Files\Shutter Encoder\Shutter Encoder.exe"`

And copy/paste the log here.
Thanks,
Paul.

**Comment by 60fpshacksrock** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\x64>"C:\Program Files\Shutter Encoder\JRE\bin\java.exe" -jar "C:\Progra
m Files\Shutter Encoder\Shutter Encoder.exe"
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: co
m.sun.java.accessibility.AccessBridge
        at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source
)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown
Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Sourc
e)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown S
ource)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown S
ource)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Un
known Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequent
ial(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Sourc
e)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Window.getToolkit(Unknown Source)
        at java.desktop/java.awt.Window.init(Unknown Source)
        at java.desktop/java.awt.Window.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
        at application.Shutter.<clinit>(Shutter.java:215)
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBr
idge
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown So
urce)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(U
nknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        ... 19 more

**Comment by paulpacifico** [comment]
Did you try to uninstall java from your computer? It seems to be related to a java conflict with other versions.

**Comment by 60fpshacksrock** [comment]
Yes, completely. 
Afterwards no Java programs would work until I re-installed after trying this program with your instructions.

**Comment by paulpacifico** [comment]
Sorry for the delay i'm was very busy.

Could try a last thing? Download this java version: https://we.tl/t-CfvsNb2Bfz

Remove the folder named "**JRE**" in Shutter Encoder installation, unzip the downloaded file replace it.

Try to start Shutter Encoder, hope it will works.

Paul.

**Comment by 60fpshacksrock** [comment]
Not sure what you did, but it now works, thank you. 
Only, now there is another issue. When I try to use "Activate the image sequence to" I get this:

FFprobe:       audio service type: main
FFmpeg: Error opening output files: Invalid argument

The reason this tool caught my attention was motion, or frame interpolation. I have trying to
find a tool that interpolate frames up to 60 while also being able to make a good quality conversion
in the process. I started using another tool called Hybrid by Selur shortly after I found this, and while
Hybrid works good, the motion interpolation it does on videos with VapourSynth or AviSynth leave less
than satisfactory results, with quite a few artifacts such as macroblocking among other things.

Another tool I used, a version of MeGUI called "MeGUI Double 2017" works and converts with better quality (and with a bitrate 
of about 1400kbps to 1600kbps, it only doubles the framerate of the video and won't allow to interpolate from
24fps or 25fps to 60. I know about ffmpeg's minterpolate feature but it is way too slow and would probably take about
two weeks or more to convert a movie because that feature only works in single core, and my PC is Daul-Core.

**Comment by paulpacifico** [comment]
Oh great!
I've just updated Java package, but be sure to replace for the next releases, i do not intend to update it from my builds (i got some bugs with newer Java packages).

"Activate the image sequence to" is made for timelapse creation not to change framerate, if you want to change framerate, use "**Conform**" from "**Advanced features**" set to "Interpolation". BUT it use minterpolate from FFmpeg which as you said is very very slow (i'm also working on dual-core).

Hope you still get to work with Shutter Encoder!
Paul!

**Comment by 60fpshacksrock** [comment]
Okay. Thanks a lot.

**Comment by lostcowboy** [comment]
So I just got this error. I uninstalled it and downloaded the latest from your website, and installed it. Got the same error again.
I am not sure when I installed Shutter Encoder, but I was not aware that it used java. I have installed Jdownloader 2 https://jdownloader.org/ which I understand uses Java from https://www.java.com/download/ie_manual.jsp. but your program uses Java from https://adoptopenjdk.net/releases.html?variant=openjdk13&jvmVariant=hotspot .
I am willing to bet that a lot of registry settings got rewritten and that is why I am getting the error message "Java Virtual Machine Launcher\ a java Exception has occurred. It does not tell me which java install is giving the error, so I cannot help you more than this. I am going to uninstall Shutter Encoder for now, and hope you can get this figured out.

**Comment by paulpacifico** [comment]
Hi,
Thanks for your feedback, did you try to remove/reinstall Java from your computer?

Shutter Encoder is installed on thousands of Windows computers with no complains about this issue, so I think it comes from your computer (but maybe I'm wrong!)

Let me know,
Paul.

**Comment by gustaveracosta** [comment]
I am having the same issue

**Comment by gustaveracosta** [comment]
I downloaded JRE contents from here https://adoptopenjdk.net/releases.html?variant=openjdk13&jvmVariant=hotspot and it fixed. Thanks lostcowboy
