### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by rgabbo** [paulpacifico/shutter-encoder#225]
Hi.
I noticed a typo here https://www.shutterencoder.com/documentation/#Functions-H.265. More specifically, in the part where H.265 codec is described should be corrected because it says H.264. I'm attaching a screenshot

![Screenshot 2024-08-25 at 10-46-17 Documentation](https://github.com/user-attachments/assets/964879b1-e824-4dc9-b974-d7a0f8823dc0)

**Comment by paulpacifico** [comment]
Hi,

Thanks a lot for your feedback, that's a mistake!

I'm currently on holiday but I will correct it as soon as I'm back to home!

Best,
Paul.
