### ISSUE TITLE
[question] Editing GIFs?

### ISSUE THREAD

**Issue by 0lm** [paulpacifico/shutter-encoder#23]
Hi
Sorry if I couldnt find this feature if it existed, but what do I exactly need to select in the list to edit my gifs? When I pick "images" there is no "gif", but only "webp" in the list.
What I want to do with my gifs: Resize them. Or cut the gif to display only a specific area of the gif. Change playback speed of the gif etc.

**Comment by paulpacifico** [comment]
Hi,
Gif is available from an external package from "**Downloads**" section on the website, here is the link: https://www.shutterencoder.com/presets/GIF-Presets.zip

Drag/drop inside "**My functions**" window form **star icon**.

Unfortunately it's not currently possible to edit the Gif, you have to change speed/crop/resize with an other video codec before creating the Gif.

Paul.
