### ISSUE TITLE
Apple Silicon version still depends on Intel/Rosetta

### ISSUE THREAD

**Issue by romanr** [paulpacifico/shutter-encoder#230]
Looking at process tree it runs intel bash process under Rosetta emulation. 
Does it still use any intel specific components? in #76 mentions "ytp-dl" which is yt-dlp? I can't see it spawning anything.

**Comment by romanr** [comment]
yt-dlp is for capturing videos from websites. I never do that, why that process is spawned? and conversion is done by ffmpeg. all this software is available for Silicon.

It's running Intel bash under Rosetta in background. Bash is surely available for Silicon.

```
/private/var/db/oah/d8db2f24456a06d68bd2e/bash.aot
/usr/libexec/rosetta/runtime
/Library/Apple/usr/libexec/oah/libRosettaRuntime
/usr/lib/dyld
/private/var/db/oah/d8db2f24a59d67a5e8421e/dyld.aot
/dev/null
/dev/null
/dev/null
/Applications/Shutter Encoder.app/Contents/MacOS/Shutter Encoder
```

**Comment by paulpacifico** [comment]
I don't really understand why my app needs Rosetta because as you can see all my files are ARM64 compatible.

![rosetta](https://github.com/user-attachments/assets/57e2a2e6-270f-4175-b8ad-a002ccdb77cc)

If you have any idea... I suspect that's Java but again it's a ARM64 version.

Paul.

**Comment by romanr** [comment]
> I don't really understand why my app needs Rosetta because as you can see all my files are ARM64 compatible.
> 
> If you have any idea... I suspect that's Java but again it's a ARM64 version.
> 
> Paul.

In screenshot nothing indicates that it's Java, could be yt-dlp or realesrgan

**Comment by paulpacifico** [comment]
I suspect java because the JAR file embedded many libs too.

This is not yt-dlp or realesrgan because they are both universal arch which does not imply to use Rosetta.

**Comment by romanr** [comment]
I just checked with current version and my initial report stands; it's bash process running in Rosetta.   
Just starting Shutter encoder and not doing anything spawns bash idle process runign under Rosetta.

**Comment by paulpacifico** [comment]
Thanks, how did you check that? I don't know how can I resolve this...

**Comment by romanr** [comment]
Simply looking at processes in process monitor there's a column for "Kind" which is architecture.
Order by that column to see Intel processes;
![Activity Monitor-Activity Monitor-1222 0723@2x](https://github.com/user-attachments/assets/e29b34ae-ea0c-4c1a-bfe6-c2f867f816a9)

Next, double-click on bash or any process of interest, and select "Open files" tab;
![Activity Monitor-bash (79484)-1222 0724@2x](https://github.com/user-attachments/assets/edea8ca3-f100-48ca-a6f3-201c769d8233)

**Comment by paulpacifico** [comment]
I've finally solved this issue, thank you so much 🙏

It was the plist fault, adding:

`<key>LSArchitecturePriority</key>
    <array>
        <string>arm64</string>
    </array>`

AND changing the **CFBundleIdentifier** make the app running without Rosetta.

Happy holiday!
Paul.

**Comment by paulpacifico** [comment]
About the v18.7 the bash still run has 'Intel' because I didn't change the **CFBundleIdentifier** value otherwise the app update won't work.
But, all the backend tools now run has 'Apple' thanks to the `-arch arm64` argument when launching Java.
If you want to run bash has 'Apple' you need to rename the  **CFBundleIdentifier** from the plist file.
