### ISSUE TITLE
[REQUEST] Option to easily set common pixel aspect ratios

### ISSUE THREAD

**Issue by DesertCookie** [paulpacifico/shutter-encoder#239]
While a niche feature, it occasionally can be helpful to encode with a custom pixel aspect ratio. For example, with anamorphic footage.

As far as I can tell, you'd do that with `-setsar=4/3` to set a pixel aspect ratio of `1.33`, for instance. This behavior is a little tricky to implement with [some fallstrings](https://trac.ffmpeg.org/wiki/Scaling).

Looking at what DaVinci Resolve uses as its quick-select options (while also allowing to input a `1.xx` value manually) these would be common pixel aspect ratios:

- 1.25
- 1.33
- 1.3
- 1.5
- 1.8
- 2.0

**Comment by chenlung** [comment]
Already requested: [](https://github.com/paulpacifico/shutter-encoder/issues/13)

**Comment by paulpacifico** [comment]
This exactly what the force display checkbox does.

**Comment by DesertCookie** [comment]
Thanks a lot. I forgot to also filter for closed issues, thus not finding anything when I searched for `pixel aspect ratio`. Sorry and thanks.
