### ISSUE TITLE
High-DPI Support on Linux

### ISSUE THREAD

**Issue by sachmo-source** [paulpacifico/shutter-encoder#24]
Love the program. I am looking forward to using it on a regular basis, but unfortunately, both the appimage and apt via debian package cannot display properly on my 4K UHD display. When I look for the option to enable High-DPI with the program settings I see no such setting. I have been testing it by zooming in on my screen via an accessibility function native to my system, but this work around is imperfect. Here are some basic system specs - please tell me if you need to know more...

Kernel: 5.4.0-67-generic x86_64 bits
DIstribution:  Linux Mint 20.1 Ulyssa
Desktop Environment: Cinnamon 4.8.6
Processor: Intel© Core™ i9-9900K CPU @ 3.60GHz × 8
Graphics Card: MSI GeForce RTX 3090 VENTUS 3X OC

Everything else about the program seems to function as intended. I just have a hard time seeing anything with the gui scaled to such a small size on a relatively high resolution screen. I have attached a composite of two side-by-side screen captures of the issue in native 4K UHD, and then the non-issue in 1080p scaled to a 4K display (both sides are labeled in image). The 4K side of the composite has missing or jumbled button text and must be zoomed in by a factor of (roughly) x2 for said buttons to be easily clickable and visible. The only thing (I imagine) is necessary to re-produce the issue, is to simply run the program on a Linux machine with a 4K display. I am wondering if the program has/will have High-DPI support on Linux. Thank you for the software, and thank you for your time.

![side-by-side](https://user-images.githubusercontent.com/79201627/111891133-c9f8fc80-89c6-11eb-9528-b0e0a1f4f29a.png)

**Comment by paulpacifico** [comment]
Hi,

Thanks a lot for your feedback i really appreciate.

**Here is how to:**

- Open this file in Shutter Encoder's folder: "/Shutter Encoder/usr/bin/shutter-encoder"

- Add this line before -jar : `-Dsun.java2d.uiScale=2.0`

You should have this now: `"$parent_path/JRE/bin/java" -Dswing.aatext=true -Dsun.java2d.uiScale=2.0 -jar "$parent_path/Shutter Encoder.jar" "$@" &>/dev/null & disown`

Then start Shutter normally.

Keep me informed,
Paul.

**Comment by sachmo-source** [comment]
Thank you for the prompt reply and help. I implemented the change in code you outlined and it did indeed scale the gui properly. And the application converts as well as advertised! So I am certainly happy for now. But, since you are still actively developing the application, I wanted to let you know about some quirky behaviors I noticed once making this adjustment...

1) The application no longer allows me to drag and drop any media files once scaled. It works just fine in this regard when -Dsun.java2d.uiScale=2.0 is not implemented - but once it is - drag and drop simply never shows the '+' sign that indicates it can be added and no media file I tried can be added.

2) The application no longer uses the stock icon located in the same folder, and no longer respects the icon assigned to it via apt launcher. It simply displays the standard, blue/orange Java coffee mug icon.

I don't know much about Java, but I know some functions like '-Dsun.java2d.dpiaware=false' either never worked or are now deprecated - so I don't see any other feasible way to affect scaling without affecting the aforesaid properties. You probably already know this (since you know my operating system), but just in case - here is my version of Java...

victor@computer:~$ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

Thanks again for the help, and I look forward to using your app more and donating and contributing in the future.

**Comment by paulpacifico** [comment]
Great! thanks for the feedback,

1. That's really strange, there is no relation with ui scaling, did you start with different rights or account?
2. The Linux version is pretty new, i've developed Shutter for it because people requesting me. I need to tweak a bit the app for Linux until everything become perfect. I'm very busy but i keep this in my to do list, thanks.

Shutter is only using embedded java version (which is java 13 by the way). I can update it to a newer version which maybe will automatically scale the UI but i can't check my self with a standard screen. Also i have some troubles with newer java version and the embedded video player in Shutter.

Anyway, thanks a lot for this i try to do my best for Linux!

Best,
Paul.
