### ISSUE TITLE
Cut without re-encoding, support for multiple clip segments

### ISSUE THREAD

**Issue by Leroy-X** [paulpacifico/shutter-encoder#240]
Currently, it seems only a single segment is supported. I’d like to see support for multiple segments. [LosslessCut](https://mifi.no/losslesscut/) handles this by exporting multiple segments and then merging them into one. It would be great to add a similar feature.

Thanks

**Comment by paulpacifico** [comment]
You can achieve something similar using the render queue from the 3 lines icon (next to 'Start function' button) to add multiple segments then use the 'Merge' function.
