### ISSUE TITLE
Win 11. GUI does not launch when HDR is enabled

### ISSUE THREAD

**Issue by Decumber** [paulpacifico/shutter-encoder#241]
#145  

when hdr is enabled:

![231](https://github.com/user-attachments/assets/dfd21e4d-f9e9-47bc-b4a1-6095bf4874cd)
![2024-10-27_19-53-10](https://github.com/user-attachments/assets/acb97e3d-cb66-4f6b-b839-bbd734894f45)

when hdr is off:
![1234](https://github.com/user-attachments/assets/e7331267-0e6c-4c9d-b2c3-533ae2391760)
![2024-10-27_19-56-43](https://github.com/user-attachments/assets/c8b9b26f-28ae-456c-91d6-108e0fd32087)

**Comment by Sergo1217** [comment]
+1
![image](https://github.com/user-attachments/assets/191d5cb7-3808-45ce-a2de-be3e2cc3f66a)
![image](https://github.com/user-attachments/assets/7a247637-f625-4f7a-a895-249bddad10fc)

**Comment by paulpacifico** [comment]
Hi,

Thanks for the screenshots, could you try this:

Open the shortcut properties then copy/paste this in the "Target" box:

"C:\Program Files\Shutter Encoder\JRE\bin\javaw.exe" -Xmx4G -Dsun.java2d.opengl=false -Dswing.aatext=true -Djavax.accessibility.assistive_technologies -Djavax.accessibility.screen_magnifier_present=false -jar "Shutter Encoder.exe"

Paul.

**Comment by Decumber** [comment]
> Hi,
> 
> Thanks for the screenshots, could you try this:
> 
> Open the shortcut properties then copy/paste this in the "Target" box:
> 
> "C:\Program Files\Shutter Encoder\JRE\bin\javaw.exe" -Xmx4G -Dsun.java2d.opengl=false -Dswing.aatext=true -Djavax.accessibility.assistive_technologies -Djavax.accessibility.screen_magnifier_present=false -jar "Shutter Encoder.exe"
> 
> Paul.

It worked
