### ISSUE TITLE
Experiencing 2 Issues with Encodes

### ISSUE THREAD

**Issue by Jackaloopt-OG** [paulpacifico/shutter-encoder#242]
As described from previous Reddit post.

1) Encoder never officially concludes job. File is generated correctly but witnessing spinning beach ball when encoder shows 100% complete. This occurs on every job and have to quit application before proceeding with new encode.

2) Encoder generates .log and .log.mbtree files for every single file generated. This occurs with every encode. I have not experienced this in previous versions of the app and tried to find a setting to turn this off but was unsuccessful.

Created an account so that I can send you the log file.
[Shutter Encoder Console.txt](https://github.com/user-attachments/files/17612548/Shutter.Encoder.Console.txt)

**EDIT:** Added computer hardware/software specs.

Shutter Encoder version 18.5

macOS Monterey 12.7.6, Mac Pro (Late 2013), Processor: 2.7 GHz 12-Core Intel Xeon E5, Memory: 64GB, Graphics: AMD FIREPRO d700 6GB

**Comment by paulpacifico** [comment]
Can you check if Shutter Encoder has full disk access and permissions?

Paul.

**Comment by paulpacifico** [comment]
I never saw this issue before, could you try to encode your file on another drive to understand where the issue came from?

**Comment by Jackaloopt-OG** [comment]
Test 1: Moved source file to different drive and encoded file to same source folder - successful.
Test 2: Created new folder on desktop drive. Moved source file to new folder and encoded file to same source folder - successful.
Test 3: Used source file from original folder on desktop drive and encoded file to different drive - successful.
Test 4: Used source file from original folder on desktop drive and encoded file to different folder on same drive - successful.
Test 5: Used source file from original folder on desktop drive and encoded file to same folder - failed.

Sharing & Permissions for original folder on desktop drive and successful test folders on same and other drives are the same.

**Comment by paulpacifico** [comment]
Thanks a lot for all this test, can you just add a suffix to the output file and try? I think the problem can become from the same name as the folder but not sure.

**Comment by Jackaloopt-OG** [comment]
Absolutely happy to help.

So I have narrowed down to what the issue is. It's regarding permissions or more specifically, the date as to when permissions were granted access to the desktop drive.

After running a number of different tests, listed below are the ones that I had done multiple times that made me come to my conclusion:

1. If I create a new folder on the desktop and move the source file to this new folder and encode to the same folder, it works. 
2. If I select a completely different, pre-existing folder on the desktop that was created some time ago in the past and move that source file to that folder and encode to that folder, it fails.
3. If I move the source file to an external drive and place it in a pre-existing folder that was created in the past and encode it there, it succeeds.

After confirming this error, I then completely uninstalled Shutter Encoder, emptied the trash, restarted the computer, reinstalled Shutter Encoder and immediately checked if the Full Disk Access permissions were granted which they were. I then ran the same three tests listed above again to confirm that even when Shutter Encoder is granted Full Disk Access since the beginning of installation, it will still error in the same way.

This also explains why when I had used Handbrake, that it sometimes would prompt me for permission to the source folder and sometimes it would not as I was experiencing that when I was using it on the same video.

**Comment by paulpacifico** [comment]
This is definitely a write access that is not allowed on older folders. Maybe you have created this folders with an other session which required admin rights.

Shutter Encoder should also ask for permission. Currently I don't have more solutions :-/

**Comment by Jackaloopt-OG** [comment]
Thank you for the update Paul. I will use the workarounds next time this may come up. Appreciate all the help and your time.
