### ISSUE TITLE
Mention on the site that it's open source

### ISSUE THREAD

**Issue by thibaultmol** [paulpacifico/shutter-encoder#249]
I just came across this program and what I find very strangle is that your website doesn't mention ANYWHERE that it's open source.
It mentions that it's based on certain open source projects but it doesn't actually say anything about the program itself being open source. (it only mentions it's free.... which usually to me, if i see a free program that isn't open source, red flags go off).

So it's only because of someone online that i trust posting about it that i even realized it was open source

**Comment by paulpacifico** [comment]
https://www.shutterencoder.com/#sources
