### ISSUE TITLE
Fail on convert color space since 18.4

### ISSUE THREAD

**Issue by chronocn** [paulpacifico/shutter-encoder#250]
Hi

I shot HLG videos by Sony Alpha 1 camera which can be displayed as "Transfer characteristics: HLG" color space from Mediainfo. 
I want to use Shutter Encoder (Windows) to encode it and output as "Transfer characteristics: PQ" color space by select "Rec2020 PQ 10bits" (also apply a custom LUT) in the settings.
When I used version 18.3, it operated correctly and transfer from HLG to PQ as expected。
However, from version 18.4, it can not operated correctly, which output file still showed color space "Transfer characteristics: HLG".

I tried to replace FFmpeg in the Library, and I found if I using ffmpeg-7.0.2 it would operated correctly. If I using ffmpeg-7.1 it would not operated correctly.

This is a sample shoting as HLG color space.
[20241010_A1_4592.zip](https://github.com/user-attachments/files/18053073/20241010_A1_4592.zip)

Best wished.

**Comment by paulpacifico** [comment]
Hi,

Thanks a lot for your feedback, indeed it doesn't seem to work on your file. Apparently ffmpeg has a new parameter for colorspace, I've checked and it works better, It will be correct for the next release.

Paul.
