### ISSUE TITLE
difficult to read UI

### ISSUE THREAD

**Issue by h2dden** [paulpacifico/shutter-encoder#252]
running on Debian 12 
The UI is difficult to read. Is there a way to scale up the font? 

![deltachat-2024-12-12-200215](https://github.com/user-attachments/assets/18eb11a6-32c7-4ae2-82af-77fad0abbafc)

**Comment by paulpacifico** [comment]
Here is how to:

Open this file in Shutter Encoder's folder: "/Shutter Encoder/usr/bin/shutter-encoder"

Add this line before -jar : `-Dsun.java2d.uiScale=2.0`

You should have this now: `"$parent_path/JRE/bin/java" -Xmx4G -Dsun.java2d.uiScale=2.0 -jar "$parent_path/Shutter Encoder.jar" "$@" &>/dev/null & disown`

**Comment by h2dden** [comment]
thank you, Paul

**Comment by h2dden** [comment]
for posterity, on Debian 12 the file is located at
/usr/lib/Shutter Encoder/usr/bin/shutter-encoder
