### ISSUE TITLE
UI is not rendering properly and is unreadable

### ISSUE THREAD

**Issue by alvinek** [paulpacifico/shutter-encoder#256]
So I've downlaoded this app, version 18.6, from https://www.shutterencoder.com/ and as soon as I moved mouse over app I got greeted with this look:

![image](https://github.com/user-attachments/assets/52a4ca88-0839-4d4f-9fea-019e47c4ae97)
![image](https://github.com/user-attachments/assets/0b26bd48-cd2b-4671-ac41-96b6c5697012)
![image](https://github.com/user-attachments/assets/42e68975-0692-4d11-b9b2-ee24ae49afbc)

Seems like something went very wrong. When I resize window, it goes back to normal, but as soon as I hover mouse over it reverts to this unreadable look. Since it's my first app run, no idea what went wrong, it's default installation, I installed it 5 mins ago. I will be happy to help with diagnosing what is going wrong on my side.

**Comment by paulpacifico** [comment]
Do this:

Open the shortcut properties then copy/paste this in the "Target" box:

`"C:\Program Files\Shutter Encoder\JRE\bin\javaw.exe" -Xmx4G -Dsun.java2d.opengl=true -Djavax.accessibility.assistive_technologies -Djavax.accessibility.screen_magnifier_present=false -jar "Shutter Encoder.exe"`

Paul.

**Comment by alvinek** [comment]
It works, ran it from command line and everything is okay. Fixed my shortcut. Thanks
