### ISSUE TITLE
Opus audio codec is not available when h.265 video codec is selected

### ISSUE THREAD

**Issue by Shakil-Shahadat** [paulpacifico/shutter-encoder#27]
Happens regardless of container format. Possibly not all container can take that, but mkv can for sure.

**Comment by paulpacifico** [comment]
Thanks for the feedback, i will add this audio codec to H.265 as soon as i can.

Paul.

**Comment by Shakil-Shahadat** [comment]
Opus is now available. Thanks.

**Comment by paulpacifico** [comment]
You are very quick! Thanks for testing it!
