### ISSUE TITLE
[feature] WEBP Options

### ISSUE THREAD

**Issue by brunocalado** [paulpacifico/shutter-encoder#31]
Hi.

Thank you for this great software!

Is it possible to add quality options for WEBP in the same way JPG?
![image](https://user-images.githubusercontent.com/4999783/118315100-72a97100-b4cb-11eb-9d06-29842841a110.png)

WEBP is a better and smaller format for web and I use it in the place of jpg.

There is no quality option for webp:
![image](https://user-images.githubusercontent.com/4999783/118315191-940a5d00-b4cb-11eb-8b52-f0e72045bf44.png)

Thank you.

**Comment by paulpacifico** [comment]
This option has been added since version 15.1
