### ISSUE TITLE
FLAC audio with video files | Chroma sub-sampling

### ISSUE THREAD

**Issue by DesertCookie** [paulpacifico/shutter-encoder#35]
It'd be great to have FLAC as an option for audio when converting videos. Other common formats like PCM are missing too.

Right now, for example, I'd like to convert a bunch of files to H265 10bit to save on space. With 1080p files, half of the file is the 24bit PCM audio. I'd like to convert that to 16bit PCM or FLAC to substantially decrease file size.

**Comment by paulpacifico** [comment]
Thanks for your feedback,
Yes someone also asked me on reddit to add FLAC for this codec, I will try to add it for the next release I have many request but this seems useful.

Keep connected!
Paul.

**Comment by DesertCookie** [comment]
One more question to not have to create a new issue:

Is there a way to specify chroma sub-sampling? My camera records in 4:2:2 and I'd like to archive my footage in 4:2:2 as well. It is my understanding though, that the default for most delivery codecs is 4:2:0.

**Comment by paulpacifico** [comment]
It depends of your output codec, most of editing friendly codecs are 422. But I suppose you're looking for high compression like H.264/5 then you can do 422 from "Advanced features" section then "Force profile" -> "High422".

Paul.

**Comment by chenlung** [comment]
It's better to create a new ticket/issue so each item is filed properly for others to find.

**Comment by paulpacifico** [comment]
Flac audio codec will be available with H.264/5 codecs with the next release.
