### ISSUE TITLE
Shutter Encoder does not appear in Windows Open With

### ISSUE THREAD

**Issue by JNavas2** [paulpacifico/shutter-encoder#36]
An issue (relatively minor) is that Shutter Encoder does not appear in Windows Open With
(the expected behavior) after it has been invoked that way.
![4WAv7Mt](https://user-images.githubusercontent.com/14850792/127018971-e392126d-b342-4c91-b916-61b2de5dabca.png)
It matters because Open With can be a much easier way to invoke Shutter than Browse after launching.

I debugged a similar issue years ago, and I think I finally figured out that it has something to do
with the installer and packaging of the executable file, but I'm afraid I don't remember the details. 
Shutter does have Open With entries in the Registry, but one is for Java, which I think is part of the problem.
![PJbyV5M](https://user-images.githubusercontent.com/14850792/127019085-fda839e9-feff-4ad5-886c-06d744f008a0.png)
![NhZY0te](https://user-images.githubusercontent.com/14850792/127019100-6f643247-8a92-40e4-a650-2662f1d8ad05.png)

My own work-around has been to add Shutter Encoder as an Action to video file types:
![FWbRprN](https://user-images.githubusercontent.com/14850792/127019139-59082b17-8d84-47ec-89cf-89bf3257f0be.png)
But most users won't know how to do that, so **this might be a good option for Shutter**.

OS Name: Microsoft Windows 8.1 Pro
Version: 6.3.9600 Build 9600
System Type: x64-based PC
Processor: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM): 32.0 GB
Drive: Samsung PM961 SSD 512 GB PCIe (NVMe)

**Comment by paulpacifico** [comment]
I've used an other method to add Shutter Encoder to the context menu (as shown on your last screenshot), it works for files & folders, and will be available for the next release which coming soon.

Thanks for all!
Paul.

**Comment by JNavas2** [comment]
Sounds good, if there is flexibility: 
- I do not want a Shutter action on _folders_.
- On _files_, I only want a Shutter action on Video Type.

Which is what I have now manually.
Thank you.
### Environment
- OS Name: Microsoft Windows 8.1 Pro
- Version: 6.3.9600 Build 9600
- System Type: x64-based PC
- Processor: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
- Installed Physical Memory (RAM): 32.0 GB
- Drive: Samsung PM961 SSD 512 GB PCIe (NVMe)

**Comment by JNavas2** [comment]
Unfortunately, the new Windows Action of Shutter Encoder in 15.3 appears on _non-Video_ file types (e.g., CMD).
It should _only_ appear on file types that Shutter Encoder actually supports, and it should be _controllable by the user_.
This is at best _bad behavior_ if not a _bug_. Please Reopen this issue.
It's sufficiently annoying that I'm _reverting to 15.3 Beta_ (with manual Action). (You're losing me.)
