### ISSUE TITLE
Output Default Folder not honored (Windows)

### ISSUE THREAD

**Issue by JNavas2** [paulpacifico/shutter-encoder#38]
I've set my Desktop as the Default in all three Outputs:

![FeaD6h1](https://user-images.githubusercontent.com/14850792/127171263-217df3c4-b4ee-4df2-b3a7-82c9d234f6c8.png)

However, when adding a video, whether by Browse or drag-and-drop,
that default is not set. Instead I get Same as Source, and must change that manually:

![FeaD6h2](https://user-images.githubusercontent.com/14850792/127171011-ddaf1684-f3e1-42b3-b601-d0b16c3f6b7b.png)

Is this a bug or cockpit error?
### Environment
- OS Name: Microsoft Windows 8.1 Pro
- Version: 6.3.9600 Build 9600
- System Type: x64-based PC
- Processor: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
- Installed Physical Memory (RAM): 32.0 GB
- Drive: Samsung PM961 SSD 512 GB PCIe (NVMe)

**Comment by paulpacifico** [comment]
This is not a bug, "~\Desktop" is the default folder when you click on "Change" from destination section.

But if you change the default output to anything else, it will open Shutter Encoder with your selected folder.

This work like that because I want to keep "Same as source" when you're using SE for the first time, it helps beginner to find their files and advanced users can unselect "Change" to get the "Same as source" destination.

**Comment by JNavas2** [comment]
@paulpacifico 
> This is not a bug, "~\Desktop" is the default folder when you click on "Change" from destination section.
> But if you change the default output to anything else, it will open Shutter Encoder with your selected folder.
> This work like that because I want to keep "Same as source" when you're using SE for the first time, it helps beginner to find their files and advanced users can unselect "Change" to get the "Same as source" destination.

I understand, but with respect, see that (intended) behavior as poor UX, because I have set a Default folder, and it's not being honored. I don't want some other folder. I want the output to go to my Desktop, _without my having to remember to click something_. I have no problem with Shutter showing "Same as source" when first invoked, but when I _explicitly_ set my Desktop as the Default, then that should be honored thereafter without my having to click Change _each time_.
From a UX perspective, I think:
- Change should mean to a folder _other than_ (not to) the Default.
- "Same as Source" should be a Default _option_, the initial setting.

I've already had a big problem when I forgot to click Change—my source folder is on a virtual Google Drive, which _uploaded the output_ as a result, consuming lots of bandwidth, interfering with other important file transfers, and there's no practical way of canceling that upload, which _I did not want_.

I think a default should be just that, not a starting point for Change. But whatever you call it, _I want a way to have my Desktop as the output starting point, every time_ (as I can do in HandBrake).

p.s. I even think Desktop is a better default for beginners.
