### ISSUE TITLE
Add option to remove duplicate frames

### ISSUE THREAD

**Issue by gabriellluz** [paulpacifico/shutter-encoder#4]
Hi.

Can you add an option to remove duplicate frames? Or how can I add it myself?

There's an option which I use that remove duplicate frames and save some kilobytes:
`ffmpeg -i input.mp4 -vf mpdecimate,setpts=N/FRAME_RATE/TB out.mp4`

**Comment by paulpacifico** [comment]
Hi,

Thank for your feedback, 
Does using "**Conform:**" checkbox (from any video codec) set to "**Drop**" mode remove duplicated frames ? 

I didn't use mpdecimate for now i will make some research to understand what it does exactly.

For now you can write your own ffmpeg command to Shutter Encoder. Write ffmpeg **without** providing input and output into "**Choose function**" combobox, ex : `ffmpeg -vf mpdecimate,setpts=N/FRAME_RATE/TB -c:v libx264 -b:v 5000k -an`

Thanks,
Paul.

**Comment by gabriellluz** [comment]
I'm afraid the drop function only remove frames in order to achieve a specific framerate and if you watch the video, it's easy to notice. It does not remove duplicate frames. The process of removing actually removes just some of them. Let's say we have a presentation recorded in mp4 video. In that presentation, we have a slide showing some information for about 30 seconds. Removing duplicate frames will basically discard identical frames and use the remaining frames as reference, let's say we 930 frames, it will remove some frames but keeping some frames as reference. Users won't notice the difference and file will be playable, at least for me, it worked on all devices I have (PS3, DVD Player, Tablet etc).
Also, users will have some impact on filesize especially for mp4 used for slideshows, audiobooks, cartoons, japanese animation etc.

**Comment by paulpacifico** [comment]
Hi gabriellluz,

v14.3 is out! with your recommandation labeled under: "**Remove duplicate frames**" under "**Advanced features**".

Thanks a lot for this.

Note: If you're using v14.2 you need to update [manually to v14.3](https://www.shutterencoder.com/en/#downloads)

Paul.
