### ISSUE TITLE
FLACs are broken (for video)

### ISSUE THREAD

**Issue by DesertCookie** [paulpacifico/shutter-encoder#48]
There is an issue with the recently added functionality to use FLAC as audio codec when encoding a video.

- Source file: H265 10bit 100Mb/s, PCM 24bit 48KHz
- Output file: H265 10bit Q10, FLAC 24bit 48KHz

While VLC plays back the resulting file fine it does not show up in the expected way in MediaInfo and straight up causes DaVinci Resolve to crash whenever touching the file.

MediaInfo (expected) - ShutterEncoder FLAC:
```
Format                                   : FLAC
```

MediaInfo (got) - ShutterEncoder H265+FLAC:
```
Format                                   : fLaC
Codec ID                                 : fLaC
```

As a workaround I've resorted to copying the audio stream and then remuxing it to ALAC using XMediaRecorde.

**Comment by Augusto7743** [comment]
That issue not only happen with FLAC, but also in video formats not are available the video bitrate value.
Also I see some converted files to H.264 not showing some video details in MediaInfo, but showing all video details in SMPlayer.
An issue with MediaInfo ? Only Shutter Enconder using up to date tools and other softwares old version with bugs ?
