### ISSUE TITLE
Multi audio channel sets back to default once conversion is cancelled or preset is applied.

### ISSUE THREAD

**Issue by manjunath7472** [paulpacifico/shutter-encoder#5]
Hi paul,
I have also created something similar but urs is kinda advanced and i liked it. 

**FEATURE**
Needed to set individual output locations for input files like below.
input 1 to output 1
input2 to output 2
input3 to output 3
else
input 1,2,3 to output 1
input 4,5,6,7 to output 2 

**ISSUE**
Multi audio channel sets back to default once conversion is cancelled or preset is applied.
Its not getting saved.

**Comment by paulpacifico** [comment]
Hi,
Thanks for your feedback,

For your feature, why not using the "**Render queue**" accessible from the 3 lines icon (next to "Start function")? You should be able to do exactly what you need.

Thanks for the issue feedback, i will correct-it.
Paul.

**Comment by chenlung** [comment]
I would recommend filing each issue or feature report separately and title them accordingly (so others can find them easier).

**Comment by paulpacifico** [comment]
Ok thanks for this.
Paul.
