### ISSUE TITLE
[request] please add alpha support to DNxHR 

### ISSUE THREAD

**Issue by Ulf3000** [paulpacifico/shutter-encoder#50]
what the title says. if you export from davinchi its possible to save dnxhr with alpha channel. dont know if ffmpeg or your other codecs support it though

**Comment by paulpacifico** [comment]
Hi,

Thanks for your comment, unfortunately Shutter Encoder is based on FFmpeg which currently does not support the alpha channel with the DNxHR codec.

Feel free to ask,
Paul.
