### ISSUE TITLE
Rewrapping a Hap encoded .mov file to .avi does not maintain the FPS setting

### ISSUE THREAD

**Issue by rwebber** [paulpacifico/shutter-encoder#52]
I have been working with many Hap encoded .mov files, and find rewrapping these to .avi very useful in my workflow, however, recently I have noticed that the reported FPS via MediaInfo is 60fps instead of the original 30fps (.mov).
I have not found an easy way to change this back to 30fps. Hopefully this is an easy fix on your end.

**Comment by paulpacifico** [comment]
Hello,

Thanks for your feedback,

I've just tested and the same problem for me... It's non sense, unfortunately it's a FFmpeg bug (the backend tool of Shutter Encoder) and I can't do much for that.

I will update FFmpeg for the next release, I hope this will be corrected!
Paul.

**Comment by rwebber** [comment]
Thanks for looking into it and getting back to me. Much appreciated.
