### ISSUE TITLE
[translation] German translation wrong for "functionCut"

### ISSUE THREAD

**Issue by 0nelight** [paulpacifico/shutter-encoder#55]
Hi!

The german translation of the Function "Cut without Re-Encode" currently translates in german into "Schneiden Re-Encode" which means "Cut Re-Encode" which is wrong.

https://github.com/paulpacifico/shutter-encoder/blob/baf0732e29365d32a6b08b7b3deffb20d151d1d7/Languages/en.properties#L300

https://github.com/paulpacifico/shutter-encoder/blob/baf0732e29365d32a6b08b7b3deffb20d151d1d7/Languages/de.properties#L300

It should mean "Schneiden ohne Re-Kodierung" (shortest version I can came up with). Somebody better suggestions? 
Is the UI-Dropdown ok with a longer caption?

**Comment by paulpacifico** [comment]
Thanks a lot for your feedback, I'm not German but it seems you're right ;-)

The only problem is the length of the sentence which does not fit perfectly, does "Verlustfrei schneiden" is ok?

Paul.

**Comment by 0nelight** [comment]
Yes that would be correct. Maybe you could call it simply „Schneiden“ and implicit mean that this cutting is without re-encoding - which is should be when using the word cutting?

**Comment by paulpacifico** [comment]
Thanks for the quick reply, I though the same but sometimes peoples ask me if "Cut without re-encoding" is lossless so "Schneiden" only maybe too short. I go for "Verlustfrei schneiden".

Thank you so much!
Paul.
