### ISSUE TITLE
More upload services

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#57]
WeTransfer is offered, but what about others (such as Google Drive and Filemail)?

**Comment by paulpacifico** [comment]
You're right, I really want to add Google Drive but I need to find a good command line program and be able to add any account from.

Also there is more important changes to do on Shutter Encoder before adding it.

But that(s on my to do list since a while!

**Comment by chenlung** [comment]
Smash might be a recent service.
