### ISSUE TITLE
Add 10 Bit option for H265 please.

### ISSUE THREAD

**Issue by ZeroCool22** [paulpacifico/shutter-encoder#6]
The program is great!

![Screenshot_1](https://user-images.githubusercontent.com/13344308/104773368-b7a6dc00-5753-11eb-9496-0e7785dbd7b9.png)

Like StaxRip have:

![Screenshot_2](https://user-images.githubusercontent.com/13344308/104773961-9c889c00-5754-11eb-94ed-2b1dd1775767.png)

**Comment by paulpacifico** [comment]
Hi,
You will find 10 bit encoding from "**Colorimetry**" section then check "**Colorspace**" and choose a 10bits colorspace.
Paul.

**Comment by ZeroCool22** [comment]
> 
> 
> Hi,
> You will find 10bits encoding from "**Colorimetry**" section then check "**Colorspace**" and choose a 10bits colorspace.
> Paul.

Awesome. Thx!

**Comment by ZeroCool22** [comment]
What's the difference between these ones?

![Screenshot_1](https://user-images.githubusercontent.com/13344308/104812206-7956fe80-57df-11eb-9338-812f8f73e15a.jpg)

**Comment by paulpacifico** [comment]
- **709**/**2020** are actually **colorspaces**, take a look at this: [https://www.extremetech.com/wp-content/uploads/2020/01/Rec709-vs-2020.jpeg](url).

- **PQ** and **HLG** are **curves** for this colorspaces it's quite complex to explain, more infos here: [https://www.eizo.com/library/management/ins-and-outs-of-hdr/index2.html/](url)

The most common is to select **Rec. 2020 PQ 10Bits**.

Paul.

**Comment by ZeroCool22** [comment]
> 
> 
>     * **709**/**2020** are actually **colorspaces**, take a look at this: https://www.extremetech.com/wp-content/uploads/2020/01/Rec709-vs-2020.jpeg.
> 
>     * **PQ** and **HLG** are **curves** for this colorspaces it's quite complex to explain, more infos here: https://www.eizo.com/library/management/ins-and-outs-of-hdr/index2.html
> 
> 
> The most common is to select **Rec. 2020 PQ 10Bits**.
> 
> Paul.

Thx!

**Comment by ValeoMooha** [comment]
Hi Paul. 
What would be the best practise to preserve original camera Color Space and Gamma, like Panasonic V-Log V-Gamut or Sony S-Log3 S-Gamut3Cine?
All I want to do is to downscale file from 4K to 1080p (50%) preserving everything there is in the original file.
