### ISSUE TITLE
Audio missing from merged video file.

### ISSUE THREAD

**Issue by dante987** [paulpacifico/shutter-encoder#62]
I merged 2 video files. They had the same resolution (Frame width & height), but different Frame Rate.

One was 30 frames/second (Lets say Video A). 
The other was 29.98 frames/second (Lets say Video B).

After merging these two when I played the merged file, the audio was missing from the part when B video started playing.

Now I am really worried because I have been merging video files like this for a very long time and have merged many many videos, but never really played the merged file to check. :(

**Comment by paulpacifico** [comment]
Hello,

Your input videos should have the same codec/scale/framerate which is why it does not work properly with differents framerates.

Paul.

**Comment by dante987** [comment]
But then I used "Avidemux" and the audio was there.
