### ISSUE TITLE
[enhancement] Web video only supports YouTube

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#7]
Because there are many video hosting platforms (Dailymotion, Vimeo, etc), it should be stated that Shutter Encoder only supports YouTube.

Using Shutter Encoder 14.6 - Mac 10.11.6.

**Comment by paulpacifico** [comment]
The backend tool for "Video web" function is youtube-dl which support much more website than only youtube!

**Comment by chenlung** [comment]
I see. Thanks for the clarification, Paul.
