### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by kiencuongpo** [paulpacifico/shutter-encoder#73]
I don't see the overlay
![ảnh](https://user-images.githubusercontent.com/102970802/168346967-8202568b-3c1a-4fbe-bc9a-f94b5865ff4a.png)

**Comment by paulpacifico** [comment]
Please read the changelog, you will find it from 'Edit media content' checkbox.

Paul.

**Comment by kiencuongpo** [comment]
How to fix "Preview not avaliable"
![ảnh](https://user-images.githubusercontent.com/102970802/168391801-b6930349-f7e0-4183-907e-5b1fbedf58e9.png)

I can't see the subtitles in this
![ảnh](https://user-images.githubusercontent.com/102970802/168392250-1a79b57b-7767-4fe3-a789-6f313a06ace5.png)

**Comment by paulpacifico** [comment]
I currently do not find a solution to preview .ass subtitles but if you encode your file, they will be displayed.

I should maybe be more clear on this info box.

Paul.
