### ISSUE TITLE
Asks for Rosetta on Mac M1

### ISSUE THREAD

**Issue by kausar007** [paulpacifico/shutter-encoder#76]
Even though I downloaded the Apple Silicon version. After installation when I start the application it says "To open 'Android File Transfer', you need to install Rosetta"

**Comment by paulpacifico** [comment]
Yes that's normal because some tools still need Rosetta like ytp-dl which is the "**Web video**" function (x86 process).
But most of processes are compiled for Apple Silicon no worry.
So you need to install Rosetta anyway.
