### ISSUE TITLE
The In/Out points don't work properly when cutting video.

### ISSUE THREAD

**Issue by werewolfgold** [paulpacifico/shutter-encoder#77]
I'm using Windows 64-bit on a Windows 10 (21H2) machine.

Often times, when using "cut without re-encoding", the in-out points won't be respected on the edited video. After rendering the video, it will have a second before and/or after the endpoints.

So, for example, if you only wanted to snip off one or two seconds from a video, it might just spit out an exact copy of the video that you wanted to cut in the first place. 

Sometimes it will work correctly if I reload the video and try again, so I don't know what's causing the issue. I'd be grateful if you could look into it. Thanks in advance.

**Comment by paulpacifico** [comment]
This is because your file is probably a compressed video which can be cutted only on key frames (see Group Of Pictures explanation), so Shutter cut your video at the closest keyframe.

You can use '<' & '>' buttons to jump to the next keyframe.

Paul.
