### ISSUE TITLE
[enhancement] Grey out Filter when performing Analysis functions

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#8]
The Filter drop-down box serves no purpose when performing the functions in Analysis.

**Comment by chenlung** [comment]
What about the functions in Cut without re-encoding?

Despite selecting another extension in Filter, the resultant file was that of the original extension.

**Comment by paulpacifico** [comment]
Refer to this: https://www.shutterencoder.com/documentation.html#Filter
