### ISSUE TITLE
Keep sub-black and super-white data

### ISSUE THREAD

**Issue by DesertCookie** [paulpacifico/shutter-encoder#81]
Is there an option to keep sub-black and super-white data like in DaVinci Resolve?

Does ShutterEncoder keep this data by default? I am especially interested in that for H.264, H.264, and VP9.

**Comment by paulpacifico** [comment]
I think you're looking for '**Force output:**' '**0-255**', this option is only available for H.264 & H.265 codecs.

Paul.

**Comment by DesertCookie** [comment]
I am trying to convert a DNxHR HQX source which is 12bit 4:2:2 with sub-blacks and super-whites written to the file.

When trying to render H.264 or H.265 with the `Force outpue: 0-255` toggle I always get the following error:

```
FFprobe: Unsupported codec with id 0 for input stream 1
FFmpeg: Unknown pixel format requested: yuvj420p10le.
```

**Comment by paulpacifico** [comment]
Sorry for the delay I was on holiday.

This happens because you can't force the 0-255 levels with the 10bits colorpsace.
 
Paul.

**Comment by DesertCookie** [comment]
No worries.

Interesting. Does 10bit always have 0-255 levels then? I know my camera encodes 10bit H.265 with 0-255 levels - I'd like to keep it that way through re-encoding.

**Comment by paulpacifico** [comment]
No 10bit does not mean 0-255 levels.
This is a limitation from Shutter Encoder itself but using '**Convert levels**' from '**16-235**' to '**0-255**' inside '**Colorimetry**' section should work.
Paul.

**Comment by DesertCookie** [comment]
Coming back to this, I've noticed some gamma shifting with `Convert levels`. The footage gets quite a bit darker and does not correspond to what I color graded and exported. The exported footage does use 0-1023 levels.

![with level convert](https://github.com/paulpacifico/shutter-encoder/assets/17095983/3091991e-c280-41d8-b479-697a3d56f829)
![no level convert](https://github.com/paulpacifico/shutter-encoder/assets/17095983/36f1d8ab-293d-4790-9216-8ea49993f322)
