### ISSUE TITLE
No movie to GIF conversion!? Am I looking in the wrong place?

### ISSUE THREAD

**Issue by user897943** [paulpacifico/shutter-encoder#86]
Thanks, first of all! Amazing app. I donated before as I've been using this app for at least a couple of years, it's flawless for my use case.

I was sure I saw GIF as an option in the past, has this been removed? Or am I just confused here? I looked in the image options and animated GIF is missing...

If I am confused and there is no video to animated gif conversion please implement this, it would be really useful to post in forums for example.

**Comment by paulpacifico** [comment]
Hi, Thanks for your feedback,
Sorry for the delay I was on holiday.

The gif export is an external package that you can find at the bottom of the downloads section from the official website: https://www.shutterencoder.com/fr/#downloads

Paul.
