### ISSUE TITLE
[bug] Video download faulty

### ISSUE THREAD

**Issue by Aeolia-Schenberg** [paulpacifico/shutter-encoder#87]
YouTube dl hello I found a problem with this which cannot load all the video which exceeds between 5 to 3 minutes of video it loads but the sound is annoying and sometimes it misses the loading it created  artifacts in the video incorrectly loaded it would be better to pass on YouTube dlp which seems to better manage this function

**Comment by paulpacifico** [comment]
I've just uploaded the v16.3 version, please let me know if it works better, if not give me your OS and send me the URL.

Paul.

**Comment by Aeolia-Schenberg** [comment]
hello I just tested it's even better than before and with YouTube dlp we can finally load heavy videos thank you for this update
