### ISSUE TITLE
[bug] Step one frame backwards stopped working since v16.3

### ISSUE THREAD

**Issue by Hyperion2400** [paulpacifico/shutter-encoder#88]
First of all, thanks for this great tool. It's the best video converter I have found to date. 👍

A few days ago I updated to v16.3 and since then I can't step backwards by a single frame anymore. Stepping forwards still works.

[shutter encode bug.webm](https://user-images.githubusercontent.com/34254020/190389141-6faf012f-3e98-419a-ad10-8c3971c0421d.webm)

PS: I took a look at the commits and you've been using the same commit message for months.

**Comment by paulpacifico** [comment]
Thank you so much for this bug, I've just corrected it yesterday night and re-upload to the same version, so please re-download Shutter Encoder from the official website.

Thanks again,
Paul.
