### ISSUE TITLE
Improper directory name on Linux

### ISSUE THREAD

**Issue by eson57** [paulpacifico/shutter-encoder#89]
Hi,
I'm trying to translate and therefore test Swedish translation for your software, and found an issue in directory naming.
The directory `/usr/lib/Shutter Encoder` doesn't work wery well on linux os's, because of the space in `Shutter Encoder`. 
For example I can't copy files on command line like 
`sudo cp sv.properties /usr/lib/Shutter Encoder/usr/bin/Languages/sv.properties`. 
Because of the space in Shutter Encoder, I get the error - 
`cp: target 'Encoder/usr/bin/Languages/sv.properties' is not a directory'`.

I propose you just skip the space and name the directory `ShutterEncoder`.

**Comment by paulpacifico** [comment]
Hi,
Thanks a lot for trying to translate SE to Swedish, for the space issue it should be resolved by using an anti-slash before the space like so: `sudo cp sv.properties /usr/lib/Shutter\ Encoder/usr/bin/Languages/sv.properties`

Keep me informed,
Paul.

**Comment by eson57** [comment]
Thanks! I didn't know about that.
