### ISSUE TITLE
[bug] Buttons overlap in Set In / Out window

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#9]
![Buttons overlap in Set In : Out window](https://user-images.githubusercontent.com/2973439/106417451-017a0c80-644c-11eb-8222-d007ab489109.jpg)

Using Shutter Encoder 14.6 - Mac 10.11.6.

**Comment by chenlung** [comment]
It depends on the size of the window.

When maximised it doesn't seem a problem. If the window is small, however, then buttons can even begin to drift outside.

**Comment by paulpacifico** [comment]
Corrected with the next release (v15.1).
