### ISSUE TITLE
MP3 files buggy

### ISSUE THREAD

**Issue by 0lm** [paulpacifico/shutter-encoder#95]
I noticed when I try to edit or work on solely mp3 files, the "edit media content" feature is not working properly. Playing the mp3 file in that feature is robotic and slowed down. This happens to many mp3 files. Some of them work properly, but majority is bugged. What could be the reason?

[Here](https://mega.nz/file/lxEDFSDD#fHYZVccWxSXO-BdJZsmT38B3yY-pIgSrtFJ8iMFVjtY) is a simple test file (an example mp3 from a short soundboard clip)

**Comment by paulpacifico** [comment]
Hi,

Thanks for your file, I have absolutely no issue to work with it on a Mac.

Does your computer is old?

Paul.

**Comment by 0lm** [comment]
> Hi,
> 
> Thanks for your file, I have absolutely no issue to work with it on a Mac.
> 
> Does your computer is old?
> 
> Paul.

Hello there. Thanks for the reply. My computer is not old. Maybe I should have mentioned that I am on Windows 10 64bit.

**Comment by 0lm** [comment]
here some updated news: inside of shutter encoder, i converted the very same mp3 (i provided in the very first post) into opus, wav and ogg. Then I opened them 1 by 1 in Shutter encoder's "edit media content" feature. Shutter Encoder played them properly without any errors. 

Then I converted the ogg, wav and opus files into mp3 again (using shutter encoder again obviously) and played all 3 mp3's (converted form 3 different audio files) in shutte rencoder's "edit media content" features 1 by 1. result: all 3 mp3 again the same bug,: slow and broken playback.

**Comment by paulpacifico** [comment]
I've tried your workflow with many of my files and your source file, there is no problem on my side.

**Comment by 0lm** [comment]
> I've tried your workflow with many of my files and your source file, there is no problem on my side.

Thanks for your reply. Yeah I believe you. But you said at the beginning, you tested it on Mac. Right? That's Mac OS. I assume the error occurs on Windows 10 64bit only. I borrowed a friend's laptop and tested it on his Laptop, too (it has Windows 10 64bit 21H2 installed). it was exactly the same bug.

Did you try to reproduce on a Widows machine or sitll on your Mac?

**Comment by 0lm** [comment]
Okay, here some more news. Well, I am not fully sure what this means, but I kind of found a hoint how the bug is caused.
So, let me explain bfore showing: This error not only occured with mp3 files, but also with flac files for me, which had compression 0, 1 or 2. So, I compared the ffprobe log files of different compressions of flac files. And ffprob gave very awkward numbers for flac compression between 0 and 2. I dont know exactly what these numbers mean tbh, but I can see a huge gap there. The flac files can be played without any errors in media players. This really only seem to happen with the "edit media content" player in shutter encoder. I am going to post the different sections of the log files now:

flac compression 5 (playback properly without bugs):

```
pkt_duration=4608
pkt_duration_time=0.104490
duration=4608
duration_time=0.104490
pkt_pos=8301
pkt_size=15276
sample_fmt=s32
nb_samples=4608
```

--------------------------------------------------
flac compression 12 (playback properly without bugs):

```
pkt_duration=4608
pkt_duration_time=0.104490
duration=4608
duration_time=0.104490
pkt_pos=8288
pkt_size=14823
sample_fmt=s32
nb_samples=4608
```

--------------------------------------------------
flac compression 3 (playback properly without bugs):

```
pkt_duration=4608
pkt_duration_time=0.104490
duration=4608
duration_time=0.104490
pkt_pos=8288
pkt_size=15831
sample_fmt=s32
nb_samples=4608
```
--------------------------------------------------
flac compression 2 (playback buggy and broken):

```
pkt_duration=1152
pkt_duration_time=0.026122
duration=1152
duration_time=0.026122
pkt_pos=8288
pkt_size=4282
sample_fmt=s32
nb_samples=1152
```

--------------------------------------------------
flac compression 1 (playback buggy and broken):

```
pkt_duration=1152
pkt_duration_time=0.026122
duration=1152
duration_time=0.026122
pkt_pos=8301
pkt_size=4296
sample_fmt=s32
nb_samples=1152
```
